services:
  penguin-server:
    image: 522814693249.dkr.ecr.us-east-1.amazonaws.com/penguin-server:latest
    ports:
    - "7777:7777"

  redis:
    image: redis:8
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  redis_data:
