apiVersion: v1
kind: Service
metadata:
  name: penguin-server-service
spec:
  selector:
    app: penguin-server
  ports:
    - protocol: TCP
      port: 7777
      targetPort: 7777
      nodePort: 30077
  type: NodePort
